### ISSUE TITLE
vim搜索插件ctrlp

### ISSUE THREAD

**Issue by codepiano** [vimcn/vimcn.github.com#1]
插件名称：ctrlp
插件地址：https://github.com/kien/ctrlp.vim
贡献者列表：codepiano

已经翻译完成，在https://github.com/codepiano/ctrlp.vim/blob/translate-cn/doc/ctrlp.cnx
可以提交进来

**Comment by wsdjeg** [comment]
@codepiano 请看我们最新的ctrlpvim/ctrlp
