### ISSUE TITLE
我有一个想法，不知是否可取？

### ISSUE THREAD

**Issue by wsdjeg** [vimcn/vimcn.github.com#2]
我看了你们的组织有很多插件，分成了很多个仓库。试想一下，你们做成功了，有很多中文支持仓库，如果用户需要用许多个插件时就会非常吃力，需要在vimrc上为每一个插件仓库加上对应的中文支持仓库，这样就感觉跟多余。

**Comment by hotoo** [comment]
1. 你的想法是什么？
2. 你也可以直接向插件官方仓库提交 PR

**Comment by wsdjeg** [comment]
我明白将所有翻译插件仓库整合到一个，对于读写权限很不好控制，目前我的想法是利用git子模块方式，进行整合，整合出一个专门供用户使用的仓库，利用数组进行判断，用户需要何种插件的翻译。用户只需要在vimrc中加两行Plugin 'vimcn/example'
let g:vimrc_group=['ctrlp.vim.cnx','web'],'core']
匹配的逻辑我们可以写在vimcn/example/example.vim中

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/DotFiles/blob/master/vimrc

**Comment by hotoo** [comment]
不是仓库权限问题。

仓库单独维护会比较容易管理、安装。

``` viml
Bundle 'vimcn/vimwiki.vim.cnx'
```

**Comment by wsdjeg** [comment]
子模块不影响单个仓库的维护

**Comment by wsdjeg** [comment]
只是整合一个仓库提供给使用者

**Comment by hotoo** [comment]
你需要的话，可以自己维护一个。
